{% set name = "MaSuRCA" %}
{% set version = "3.2.3" %}
{% set hash_type = "sha256" %}
{% set hash_value = "fedc1c34992f47fb9b7235d9f368e6642922962fb0729c6b9443befe1c8e4ea3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source: 
  # ftp: ftp://ftp.genome.umd.edu/pub/{{ name }}/latest/{{ name }}-{{ version }}.tar.gz
  url: file:///home/nick/Downloads/MaSuRCA-3.2.3/MaSuRCA-3.2.3.tar.gz
  fn: {{ name }}-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
    number: 0

requirements:
    build:
        - gcc  # [not osx]
        - llvm  # [osx]
test:
  commands:
    - ./MaSuRCA --version

about:
  home: http://www.genome.umd.edu/masurca.html
  license: GPLv3 and others
  summary: 'MaSuRCA is whole genome assembly software. It combines the efficiency of the de Bruijn graph and Overlap-Layout-Consensus (OLC) approaches'

extra:
  recipe-maintainers:
    - nickp60
